#!/usr/bin/env python3
# Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
# All rights reserved.
# Use of this source code is governed by BSD 3-Clause license that can be found in the LICENSE file.

"""
Embeds a CA-certificate root bundle into FFmpeg's OpenSSL TLS backend so HTTPS
peer verification works with NO on-device cert file. This is required on hosts
whose OpenSSL default cert path (the build-time --openssldir) does not exist at
runtime: sandboxed macOS, iOS and Android in particular.

The CA bundle and the hand-written loader/header live in the embed_cacert/
sibling directory (cacert.pem, ca_bundle.h, ca_bundle_loader.c) — edit them
THERE, like the mpv-side pcm_tap/ and bulk_analysis/ patches.

Modifies (all under libavformat/):
  - ca_bundle.h         (copied in: extern array decls + ff_load_embedded_ca proto)
  - ca_bundle_loader.c  (copied in: the X509_STORE loader)
  - ca_bundle_data.c    (GENERATED here from cacert.pem: the PEM byte array)
  - Makefile            (OBJS-$(CONFIG_OPENSSL) += ca_bundle_data.o ca_bundle_loader.o)
  - tls_openssl.c       (#include "ca_bundle.h"; load the embedded roots whenever
                         no explicit ca_file is set, treating an empty ca_file as
                         unset so a blank tls-ca-file falls back to the bundle)

Idempotency: the text edits (Makefile, tls_openssl.c) are MARKER-guarded; the
.c/.h are (re)written every run so a refreshed cacert.pem propagates on rebuild.
Anchors that go missing raise — an ffmpeg layout change must fail loudly, not
silently drop HTTPS trust.

Usage:
    python3 patch_ffmpeg_embed_cacert.py <ffmpeg_source_dir>
"""
import os
import re
import sys

MARKER = 'MAK_EMBED_CACERT_V1'
SRC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'embed_cacert')


def generate_data_c(pem_path, dest_path):
    with open(pem_path, 'rb') as f:
        data = f.read()
    rows = []
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        rows.append('    ' + ''.join('0x%02x, ' % b for b in chunk).rstrip())
    out = (
        '/* %s — generated by patch_ffmpeg_embed_cacert.py from cacert.pem.\n'
        ' * Do not edit; refresh the bundle via update_cacert.sh and rebuild. */\n'
        'const unsigned char ff_ca_bundle_pem[] = {\n'
        '%s\n'
        '};\n'
        'const unsigned int ff_ca_bundle_pem_len = %du;\n'
    ) % (MARKER, '\n'.join(rows), len(data))
    with open(dest_path, 'w') as f:
        f.write(out)
    print('Generated: %s (%d bytes of PEM)' % (dest_path, len(data)))


def copy_static(name, dest_dir):
    with open(os.path.join(SRC_DIR, name)) as f:
        content = f.read()
    dst = os.path.join(dest_dir, name)
    with open(dst, 'w') as f:
        f.write(content)
    print('Copied: %s' % dst)


def patch_makefile(path):
    with open(path) as f:
        text = f.read()
    if 'ca_bundle_data.o' in text:
        print('Already patched: %s' % path)
        return
    pat = re.compile(r'(TLS-OBJS-\$\(CONFIG_OPENSSL\)\s+\+= tls_openssl\.o)')
    new_text, count = pat.subn(
        r'\1\n'
        r'# ' + MARKER + '\n'
        r'OBJS-$(CONFIG_OPENSSL)                   += ca_bundle_data.o ca_bundle_loader.o',
        text)
    if count != 1:
        raise RuntimeError(
            'Expected exactly 1 tls_openssl.o OBJS line in %s, found %d '
            '(ffmpeg Makefile layout changed?)' % (path, count))
    with open(path, 'w') as f:
        f.write(new_text)
    print('Patched: %s' % path)


def patch_tls_openssl(path):
    with open(path) as f:
        text = f.read()
    if MARKER in text:
        print('Already patched: %s' % path)
        return

    inc_anchor = '#include <openssl/x509v3.h>'
    if inc_anchor not in text:
        raise RuntimeError('openssl include anchor not found in %s' % path)
    text = text.replace(
        inc_anchor,
        inc_anchor + '\n#include "ca_bundle.h" /* ' + MARKER + ' */',
        1)

    old = (
        '    if (s->ca_file) {\n'
        '        if (!SSL_CTX_load_verify_locations(c->ctx, s->ca_file, NULL))\n'
        '            av_log(h, AV_LOG_ERROR, "SSL_CTX_load_verify_locations %s\\n", openssl_get_error(c));\n'
        '    } else {\n'
        '        if (!SSL_CTX_set_default_verify_paths(c->ctx)) {\n'
        '            // Only log the failure but do not error out, as this is not fatal\n'
        '            av_log(h, AV_LOG_WARNING, "Failure setting default verify locations: %s\\n",\n'
        '                openssl_get_error(c));\n'
        '        }\n'
        '    }'
    )
    new = (
        '    /* ' + MARKER + ': an empty ca_file means "use the embedded roots",\n'
        '     * not "load a file named \'\'", so treat "" as unset. */\n'
        '    if (s->ca_file && s->ca_file[0]) {\n'
        '        if (!SSL_CTX_load_verify_locations(c->ctx, s->ca_file, NULL))\n'
        '            av_log(h, AV_LOG_ERROR, "SSL_CTX_load_verify_locations %s\\n", openssl_get_error(c));\n'
        '    } else {\n'
        '        if (ff_load_embedded_ca(c->ctx) < 0)\n'
        '            av_log(h, AV_LOG_WARNING, "Failed to load embedded CA bundle\\n");\n'
        '        /* Also honour any OS trust store the platform happens to expose. */\n'
        '        if (!SSL_CTX_set_default_verify_paths(c->ctx))\n'
        '            av_log(h, AV_LOG_VERBOSE, "No system verify locations: %s\\n",\n'
        '                openssl_get_error(c));\n'
        '    }'
    )
    if old not in text:
        raise RuntimeError(
            'CA-file verify block not found verbatim in %s '
            '(ffmpeg tls_openssl.c layout changed?)' % path)
    text = text.replace(old, new, 1)

    with open(path, 'w') as f:
        f.write(text)
    print('Patched: %s' % path)


def main():
    if len(sys.argv) < 2:
        print('Usage: %s <ffmpeg_src_dir>' % sys.argv[0])
        sys.exit(1)
    ffmpeg_dir = sys.argv[1]
    avformat = os.path.join(ffmpeg_dir, 'libavformat')

    copy_static('ca_bundle.h', avformat)
    copy_static('ca_bundle_loader.c', avformat)
    generate_data_c(os.path.join(SRC_DIR, 'cacert.pem'),
                    os.path.join(avformat, 'ca_bundle_data.c'))
    patch_makefile(os.path.join(avformat, 'Makefile'))
    patch_tls_openssl(os.path.join(avformat, 'tls_openssl.c'))


if __name__ == '__main__':
    main()
