# Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
# All rights reserved.
# Use of this source code is governed by BSD 3-Clause license that can be found in the LICENSE file.

# Shared cross-compile setup for build_libmpv_linux.sh + build_libmpv_windows.sh.
# Sourced by every desktop build script. Do not run directly.
#
# Usage:
#   CROSS_BUILD_DIR=/tmp/build-foo CROSS_PREFIX_DIR=/tmp/build-foo/prefix \
#   cross_setup linux x86_64
#
# After cross_setup returns, the following are exported:
#   CROSS_OS, CROSS_ARCH, CROSS_TRIPLE, CROSS_TOOLCHAIN_KIND
#   CC, CXX, AR, RANLIB, NM, STRIP, READELF, OBJCOPY
#   (Windows only) WINDRES, DLLTOOL
#   PKG_CONFIG, PKG_CONFIG_LIBDIR, PKG_CONFIG_PATH
#   CROSS_MESON_FILE, CROSS_CMAKE_FILE
#   CROSS_AUTOTOOLS_HOST, FFMPEG_CROSS_ARGS
#
# The CFLAGS/LDFLAGS regime is the caller's responsibility.

# (target_os, target_arch) → toolchain triple
_cross_triple() {
  case "$1/$2" in
    linux/x86_64)    echo "x86_64-linux-gnu" ;;
    linux/aarch64)   echo "aarch64-linux-gnu" ;;
    windows/x86_64)  echo "x86_64-w64-mingw32" ;;
    windows/aarch64) echo "aarch64-w64-mingw32" ;;
    *) die "Unsupported target: $1/$2 (must be {linux,windows}/{x86_64,aarch64})" ;;
  esac
}

# Windows aarch64 uses llvm-mingw (clang+lld); everything else is GCC.
_cross_toolchain_kind() {
  case "$1/$2" in
    windows/aarch64) echo "llvm" ;;
    *)               echo "gnu"  ;;
  esac
}

# Main entry point. Args: 1=os (linux|windows), 2=arch (x86_64|aarch64)
cross_setup() {
  local os="$1" arch="$2"
  [[ -z "${CROSS_BUILD_DIR:-}"  ]] && die "cross_setup: CROSS_BUILD_DIR not set"
  [[ -z "${CROSS_PREFIX_DIR:-}" ]] && die "cross_setup: CROSS_PREFIX_DIR not set"
  mkdir -p "$CROSS_BUILD_DIR"

  export CROSS_OS="$os"
  export CROSS_ARCH="$arch"
  export CROSS_TRIPLE="$(_cross_triple "$os" "$arch")"
  export CROSS_TOOLCHAIN_KIND="$(_cross_toolchain_kind "$os" "$arch")"

  case "$CROSS_TOOLCHAIN_KIND" in
    gnu)
      # GCC + binutils. Triple-prefixed binaries provided by:
      #   - x86_64-linux-gnu-* / aarch64-linux-gnu-* (cross-toolchains, or
      #     symlinks to native gcc on a host of the same arch)
      #   - x86_64-w64-mingw32-* (gcc-mingw-w64 package)
      export CC="${CROSS_TRIPLE}-gcc"
      export CXX="${CROSS_TRIPLE}-g++"
      export AR="${CROSS_TRIPLE}-ar"
      export RANLIB="${CROSS_TRIPLE}-ranlib"
      export NM="${CROSS_TRIPLE}-nm"
      export STRIP="${CROSS_TRIPLE}-strip"
      export READELF="${CROSS_TRIPLE}-readelf"
      export OBJCOPY="${CROSS_TRIPLE}-objcopy"
      if [[ "$CROSS_OS" == "windows" ]]; then
        export WINDRES="${CROSS_TRIPLE}-windres"
        export DLLTOOL="${CROSS_TRIPLE}-dlltool"
      fi
      # GCC LTO needs gcc-ar / gcc-ranlib (linker plugin) to unpack bitcode .o
      # files inside static archives. Switch transparently when LTO is on.
      if [[ "${ENABLE_LTO_DEPS:-1}" != "0" ]]; then
        command -v "${CROSS_TRIPLE}-gcc-ar"     >/dev/null 2>&1 && AR="${CROSS_TRIPLE}-gcc-ar"
        command -v "${CROSS_TRIPLE}-gcc-ranlib" >/dev/null 2>&1 && RANLIB="${CROSS_TRIPLE}-gcc-ranlib"
        command -v "${CROSS_TRIPLE}-gcc-nm"     >/dev/null 2>&1 && NM="${CROSS_TRIPLE}-gcc-nm"
      fi
      ;;
    llvm)
      # llvm-mingw provides triple-prefixed clang/clang++ + binutils wrappers.
      # Path setup (PATH includes /opt/llvm-mingw/bin) is the Dockerfile's job.
      export CC="${CROSS_TRIPLE}-clang"
      export CXX="${CROSS_TRIPLE}-clang++"
      export AR="${CROSS_TRIPLE}-ar"
      export RANLIB="${CROSS_TRIPLE}-ranlib"
      export NM="${CROSS_TRIPLE}-nm"
      export STRIP="${CROSS_TRIPLE}-strip"
      export READELF="${CROSS_TRIPLE}-readelf"
      export OBJCOPY="${CROSS_TRIPLE}-objcopy"
      export WINDRES="${CROSS_TRIPLE}-windres"
      export DLLTOOL="${CROSS_TRIPLE}-dlltool"
      ;;
  esac

  command -v "$CC" >/dev/null 2>&1 || die "cross_setup: $CC not found in PATH"

  # pkg-config wrapper scoped to our prefix. PKG_CONFIG_LIBDIR (not _PATH) so
  # nothing leaks from the host's .pc files; for system audio backends the
  # caller can prepend system multiarch paths to PKG_CONFIG_LIBDIR.
  local pkg_wrapper="$CROSS_BUILD_DIR/pkg-config-${CROSS_TRIPLE}"
  cat > "$pkg_wrapper" <<EOF
#!/usr/bin/env bash
# Auto-generated by cross_setup() — do not edit.
export PKG_CONFIG_LIBDIR="\${PKG_CONFIG_LIBDIR:-${CROSS_PREFIX_DIR}/lib/pkgconfig:${CROSS_PREFIX_DIR}/lib64/pkgconfig:${CROSS_PREFIX_DIR}/share/pkgconfig}"
export PKG_CONFIG_PATH="\$PKG_CONFIG_LIBDIR"
export PKG_CONFIG_SYSROOT_DIR=""
exec pkg-config "\$@"
EOF
  chmod +x "$pkg_wrapper"
  export PKG_CONFIG="$pkg_wrapper"
  export PKG_CONFIG_LIBDIR="$CROSS_PREFIX_DIR/lib/pkgconfig:$CROSS_PREFIX_DIR/lib64/pkgconfig:$CROSS_PREFIX_DIR/share/pkgconfig"
  export PKG_CONFIG_PATH="$PKG_CONFIG_LIBDIR"

  export CROSS_MESON_FILE="$CROSS_BUILD_DIR/cross-${CROSS_TRIPLE}.meson"
  _cross_emit_meson_file "$CROSS_MESON_FILE"

  export CROSS_CMAKE_FILE="$CROSS_BUILD_DIR/cross-${CROSS_TRIPLE}.cmake"
  _cross_emit_cmake_file "$CROSS_CMAKE_FILE"

  # FFmpeg cross args. ffmpeg's --arch values: x86_64, aarch64.
  # --target-os: linux, mingw32 (mingw32 covers both x86_64 and aarch64 Windows).
  case "$CROSS_OS" in
    linux)
      export FFMPEG_CROSS_ARGS="--enable-cross-compile --cross-prefix=${CROSS_TRIPLE}- --target-os=linux --arch=${arch} --pkg-config=${PKG_CONFIG}"
      ;;
    windows)
      if [[ "$CROSS_TOOLCHAIN_KIND" == "llvm" ]]; then
        # llvm-mingw: ffmpeg's --cross-prefix can't drive clang's -target,
        # so override CC/CXX/etc. explicitly. NB: ffmpeg's configure has no
        # --dlltool option (deprecated; meson uses dlltool for libs but
        # ffmpeg generates static archives directly via $AR).
        export FFMPEG_CROSS_ARGS="--enable-cross-compile --target-os=mingw32 --arch=${arch} --cc=${CC} --cxx=${CXX} --ar=${AR} --ranlib=${RANLIB} --strip=${STRIP} --nm=${NM} --windres=${WINDRES} --pkg-config=${PKG_CONFIG}"
      else
        export FFMPEG_CROSS_ARGS="--enable-cross-compile --cross-prefix=${CROSS_TRIPLE}- --target-os=mingw32 --arch=${arch} --pkg-config=${PKG_CONFIG}"
      fi
      ;;
  esac

  export CROSS_AUTOTOOLS_HOST="--host=${CROSS_TRIPLE}"

  log "cross_setup: $CROSS_OS/$CROSS_ARCH (kind=$CROSS_TOOLCHAIN_KIND triple=$CROSS_TRIPLE)"
  log "  CC=$CC"
  log "  meson cross-file: $CROSS_MESON_FILE"
  log "  cmake toolchain:  $CROSS_CMAKE_FILE"
}

_cross_emit_meson_file() {
  local file="$1"
  local cpu_family system endian
  case "$CROSS_ARCH" in
    x86_64)  cpu_family="x86_64"  ;;
    aarch64) cpu_family="aarch64" ;;
  esac
  case "$CROSS_OS" in
    linux)   system="linux"   ;;
    windows) system="windows" ;;
  esac
  endian="little"

  {
    echo "# Auto-generated meson cross-file for $CROSS_TRIPLE — do not edit."
    echo "[binaries]"
    echo "c = '$CC'"
    echo "cpp = '$CXX'"
    echo "ar = '$AR'"
    echo "ranlib = '$RANLIB'"
    echo "strip = '$STRIP'"
    echo "nm = '$NM'"
    echo "pkgconfig = '$PKG_CONFIG'"
    echo "cmake = 'cmake'"
    if [[ "$CROSS_OS" == "windows" ]]; then
      echo "windres = '$WINDRES'"
      echo "dlltool = '$DLLTOOL'"
    fi
    echo
    echo "[host_machine]"
    echo "system = '$system'"
    echo "cpu_family = '$cpu_family'"
    echo "cpu = '$cpu_family'"
    echo "endian = '$endian'"
    echo
    echo "[properties]"
    echo "needs_exe_wrapper = true"
    if [[ "$CROSS_OS" == "windows" ]]; then
      echo
      echo "[built-in options]"
      echo "c_link_args = ['-L${CROSS_PREFIX_DIR}/lib']"
      echo "cpp_link_args = ['-L${CROSS_PREFIX_DIR}/lib']"
    fi
  } > "$file"
}

_cross_emit_cmake_file() {
  local file="$1"
  local sys_name proc
  case "$CROSS_OS" in
    linux)   sys_name="Linux"   ;;
    windows) sys_name="Windows" ;;
  esac
  case "$CROSS_ARCH" in
    x86_64)  proc="x86_64"  ;;
    aarch64) proc="aarch64" ;;
  esac

  {
    echo "# Auto-generated cmake toolchain file for $CROSS_TRIPLE — do not edit."
    echo "set(CMAKE_SYSTEM_NAME      $sys_name)"
    echo "set(CMAKE_SYSTEM_PROCESSOR $proc)"
    echo "set(TRIPLE                 \"$CROSS_TRIPLE\")"
    echo "set(CMAKE_C_COMPILER       $CC)"
    echo "set(CMAKE_CXX_COMPILER     $CXX)"
    echo "set(CMAKE_AR     $AR     CACHE FILEPATH \"Archiver\")"
    echo "set(CMAKE_RANLIB $RANLIB CACHE FILEPATH \"Ranlib\")"
    if [[ "$CROSS_OS" == "windows" ]]; then
      echo "set(CMAKE_RC_COMPILER $WINDRES)"
    fi
    echo "set(CMAKE_FIND_ROOT_PATH              $CROSS_PREFIX_DIR)"
    echo "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)"
    echo "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)"
    echo "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)"
    echo "set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)"
  } > "$file"
}

# Map internal arch (x86_64|aarch64) to the platform-specific FOLDER NAME used
# under <platform>/libs/. The user-visible directory layout uses each platform's
# canonical naming:
#   Linux   → 'aarch64' / 'x86_64'   (uname -m, CMAKE_SYSTEM_PROCESSOR)
#   Windows → 'arm64'   / 'x86_64'   (MSVC, Visual Studio, MS docs)
cross_folder_arch() {
  case "$1/$2" in
    linux/aarch64)   echo "aarch64" ;;
    linux/x86_64)    echo "x86_64"  ;;
    windows/aarch64) echo "arm64"   ;;
    windows/x86_64)  echo "x86_64"  ;;
    *) echo "$2" ;;
  esac
}
