#!/usr/bin/env python3
# Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
# All rights reserved.
# Use of this source code is governed by BSD 3-Clause license that can be found in the LICENSE file.

"""Fully remove libass from the mpv 0.41.0 build.

Background
==========

mpv 0.41 has **no** build-time switch to disable libass: subtitle/OSD
rendering always links against libass (and, transitively, freetype +
fribidi + harfbuzz). The old `sub/osd_dummy.c` stub backend that earlier
mpv releases shipped — which let the project build without libass — was
removed. So an audio-only consumer that never renders a glyph still pays
for ~0.94M of libass+freetype+fribidi core in the final binary.

This patch surgically removes libass from the build:

1. `meson.build`
   - drops the `libass = dependency('libass', ...)` line (whether or not
     `patch_optional_deps.py` already rewrote it to `required: false`);
   - removes the `libass` token from the `dependencies = [ ... ]` array;
   - removes the `'libass': true` entry from the `features` dict;
   - removes the three libass-only sources from the `files(...)` list:
     `sub/ass_mp.c`, `sub/osd_libass.c`, `sub/sd_ass.c`;
   - adds a new replacement source `sub/stub_libass.c`.

2. `sub/stub_libass.c` (new file)
   Re-implements *every* non-static symbol from the three removed files
   that is referenced by code which stays compiled, as a safe no-op /
   failure. The symbol set was derived by grepping the 0.41.0 tree:

     osd_libass.c → osd.c, player/osd.c, player/command.c, player/client.c
       - osd_destroy_backend
       - osd_get_function_sym
       - osd_mangle_ass
       - osd_get_text_size
       - osd_set_external
       - osd_set_external_remove_owner
       - osd_object_get_bitmaps

     sd_ass.c → sub/dec_sub.c, options/options.c, sub/filter_*.c
       - sd_ass                (struct sd_functions, in sd_list[])
       - mp_sub_filter_opts    (struct m_sub_options, in options table)
       - sd_ass_fmt_offset     (called by filter_sdh/regex/jsre)
       - sd_ass_pkt_text       (called by filter_sdh/regex/jsre)
       - sd_ass_to_plaintext   (called by filter_regex/jsre)

     ass_mp.c
       - mp_ass_* symbols are referenced ONLY by the three removed files,
         so they need no replacement.

   `mp_sub_filter_opts` and `sd_ass_fmt_offset` are reproduced faithfully
   (pure data / pure string parsing — no libass dependency) because the
   options subsystem walks the option table at startup and the sub
   filters call the offset helper during init. Everything else is a
   no-op / failure: with the audio-only consumer running `sid=no`,
   `vid=no`, `vo=null`, `cover-art-auto=no`, no subtitle decoder or OSD
   renderer is ever created, so these paths are unreachable at runtime.

3. `player/command.c`
   This staying file `#include <ass/ass.h>` and calls
   `ass_library_version()` in the `libass-version` property getter. Both
   the header (compile-time) and the symbol (link-time) vanish with
   libass, so the patch drops the include and rewrites the getter to
   report version 0.

Idempotency
===========

Every edit is guarded: meson edits check for the post-patch state (token
absent / line gone), the stub file is only written if missing or stale,
and command.c is guarded by a marker comment. Re-running on an
already-patched (cached) source tree is a no-op.

Usage
=====

    python3 patch_strip_libass.py <mpv_source_dir>
"""
import sys
import os


MARKER = 'MAK_STRIP_LIBASS_PATCH_V1'


# ─── sub/stub_libass.c ──────────────────────────────────────────────────
#
# Replacement translation unit. Implements every still-referenced symbol
# from the removed sub/ass_mp.c, sub/osd_libass.c and sub/sd_ass.c with
# EXACT signatures taken from sub/osd.h, sub/osd_state.h and sub/sd.h.

STUB_FILENAME = os.path.join('sub', 'stub_libass.c')

STUB_SOURCE = r'''/*
 * ''' + MARKER + r'''
 *
 * Auto-generated by patch_strip_libass.py — replacement stubs for the
 * libass-dependent translation units sub/ass_mp.c, sub/osd_libass.c and
 * sub/sd_ass.c, which this patch removes from the build.
 *
 * Every symbol below is referenced by code that stays compiled when
 * libass is stripped. Signatures are copied verbatim from sub/osd.h,
 * sub/osd_state.h and sub/sd.h. In an audio-only build (sid=no, vo=null,
 * cover-art-auto=no) no subtitle decoder or OSD renderer is ever
 * constructed, so all of these are unreachable at runtime and are
 * implemented as safe no-ops / failures.
 *
 * This file is part of mpv.
 *
 * mpv is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * mpv is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with mpv.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stddef.h>
#include <stdbool.h>
#include <string.h>

#include "mpv_talloc.h"
#include "misc/bstr.h"
#include "options/m_option.h"
#include "options/m_config.h"

#include "osd.h"
#include "osd_state.h"
#include "dec_sub.h"
#include "sd.h"

/* ───────────── replaces sub/osd_libass.c ───────────── */

void osd_destroy_backend(struct osd_state *osd)
{
    /* No libass renderer state was ever allocated. Nothing to free. */
    (void)osd;
}

void osd_get_function_sym(char *buffer, size_t buffer_size, int osd_function)
{
    /* OSD symbol glyphs require the libass osd font; report "no symbol". */
    (void)osd_function;
    if (buffer && buffer_size > 0)
        buffer[0] = '\0';
}

void osd_mangle_ass(bstr *dst, const char *in, bool replace_newlines)
{
    /* Used to escape OSD text into ASS markup. Without a renderer the
     * result is never drawn; leave the output buffer untouched. */
    (void)dst;
    (void)in;
    (void)replace_newlines;
}

void osd_get_text_size(struct osd_state *osd, int *out_screen_h, int *out_font_h)
{
    (void)osd;
    if (out_screen_h)
        *out_screen_h = 0;
    if (out_font_h)
        *out_font_h = 0;
}

void osd_set_external(struct osd_state *osd, struct osd_external_ass *ov)
{
    /* osd-overlay / OSC external ASS overlays — no backend to render to. */
    (void)osd;
    (void)ov;
}

void osd_set_external_remove_owner(struct osd_state *osd, void *owner)
{
    /* Called from client teardown; no externals were ever stored. */
    (void)osd;
    (void)owner;
}

struct sub_bitmaps *osd_object_get_bitmaps(struct osd_state *osd,
                                           struct osd_object *obj, int format)
{
    /* No bitmaps without a libass renderer. osd.c treats NULL as
     * "nothing to draw". */
    (void)osd;
    (void)obj;
    (void)format;
    return NULL;
}

/* ───────────── replaces sub/sd_ass.c ───────────── */

/* The ASS subtitle decoder driver. Registered in sub/dec_sub.c's
 * sd_list[]. init() fails so the decoder is never selected; the audio-only
 * consumer runs sid=no, so this is never even attempted. */
static int stub_sd_ass_init(struct sd *sd)
{
    (void)sd;
    return -1;
}

const struct sd_functions sd_ass = {
    .name = "ass",
    .accept_packets_in_advance = true,
    .init = stub_sd_ass_init,
};

/* Subtitle-filter option group. Referenced by options/options.c via
 * OPT_SUBSTRUCT, so the option subsystem walks this table at startup —
 * it must remain a fully valid m_sub_options. Reproduced verbatim from
 * the removed sub/sd_ass.c (pure option data, no libass dependency). */
#undef OPT_BASE_STRUCT
#define OPT_BASE_STRUCT struct mp_sub_filter_opts

const struct m_sub_options mp_sub_filter_opts = {
    .opts = (const struct m_option[]){
        {"sdh", OPT_BOOL(sub_filter_SDH)},
        {"sdh-harder", OPT_BOOL(sub_filter_SDH_harder)},
        {"sdh-enclosures", OPT_STRINGLIST(sub_filter_SDH_enclosures)},
        {"regex-enable", OPT_BOOL(rf_enable)},
        {"regex-plain", OPT_BOOL(rf_plain)},
        {"regex", OPT_STRINGLIST(rf_items)},
        {"jsre", OPT_STRINGLIST(jsre_items)},
        {"regex-warn", OPT_BOOL(rf_warn)},
        {0}
    },
    .size = sizeof(OPT_BASE_STRUCT),
    .defaults = &(OPT_BASE_STRUCT){
        .sub_filter_SDH_enclosures = (char *[]) {
            "()",
            "[]",
            "\uFF08\uFF09",
            NULL
        },
        .rf_enable = true,
    },
    .change_flags = UPDATE_SUB_FILT,
};

/* Pure string-parsing helper used by sub/filter_{sdh,regex,jsre}.c during
 * filter init. Reproduced verbatim (no libass dependency). Counts commas
 * to locate the trailing "Text" field of an ASS event line. */
int sd_ass_fmt_offset(const char *evt_fmt)
{
    int n = 0;
    while (evt_fmt && (evt_fmt = strchr(evt_fmt, ',')))
         evt_fmt++, n++;
    return n - 1;  // buffer is without the format's Start/End, with ReadOrder
}

/* Called by the sub filters only while actually decoding subtitle
 * packets. With sid=no no sub decoder exists, so these never run. Return
 * "empty / no-op" values that the callers already handle as the malformed
 * / nothing-to-do case. */
bstr sd_ass_pkt_text(struct sd_filter *ft, struct demux_packet *pkt, int offset)
{
    (void)ft;
    (void)pkt;
    (void)offset;
    return (bstr){NULL, 0};
}

bstr sd_ass_to_plaintext(char **out, const char *in)
{
    /* Contract: result.start == *out, (*out)[result.len] == '\0'. Honour
     * it for an empty result so callers that read *out don't crash. */
    if (out) {
        if (!*out)
            *out = talloc_strdup(NULL, "");
        else
            (*out)[0] = '\0';
        return (bstr){(unsigned char *)*out, 0};
    }
    (void)in;
    return (bstr){NULL, 0};
}
'''


def write_stub(src):
    path = os.path.join(src, STUB_FILENAME)
    if os.path.exists(path):
        with open(path) as f:
            existing = f.read()
        if existing == STUB_SOURCE:
            print(f'Already present: {STUB_FILENAME}')
            return
        # Stale copy from an older patch revision — overwrite only if it is
        # clearly ours (carries our marker), never clobber an unrelated file.
        if MARKER not in existing:
            raise RuntimeError(
                f'{path} exists but is not a {MARKER} stub — refusing to '
                f'overwrite.')
    with open(path, 'w') as f:
        f.write(STUB_SOURCE)
    print(f'Wrote: {STUB_FILENAME}')


# ─── meson.build ────────────────────────────────────────────────────────

def patch_meson(path):
    with open(path) as f:
        text = f.read()
    orig = text

    # (a) Drop the `libass = dependency('libass', ...)` line. Tolerate both
    #     the pristine form and the `required: false` form left by
    #     patch_optional_deps.py. Match the whole physical line.
    dep_lines = [
        "libass = dependency('libass', version: '>= 0.12.2', required: false)\n",
        "libass = dependency('libass', version: '>= 0.12.2')\n",
    ]
    dep_removed = False
    for dl in dep_lines:
        if dl in text:
            text = text.replace(dl, '', 1)
            dep_removed = True
            break
    if not dep_removed and "dependency('libass'" in text:
        raise RuntimeError(
            f"libass dependency() line in {path} has an unexpected form — "
            f"cannot strip safely.")

    # (b) Remove the `libass` token from the dependencies = [ ... ] array.
    #     Upstream writes it as the first element: `dependencies = [libass,`.
    deps_old = "dependencies = [libass,\n"
    deps_new = "dependencies = [\n"
    if deps_old in text:
        text = text.replace(deps_old, deps_new, 1)
    elif "dependencies = [libass" in text:
        raise RuntimeError(
            f"`dependencies` array in {path} lists libass in an unexpected "
            f"layout — cannot strip safely.")

    # (c) Remove the features-dict entry `    'libass': true,`.
    feat_old = "    'libass': true,\n"
    if feat_old in text:
        text = text.replace(feat_old, '', 1)
    elif "'libass'" in text:
        raise RuntimeError(
            f"`features` dict in {path} lists 'libass' in an unexpected "
            f"layout — cannot strip safely.")

    # (d) Remove the three libass-only sources.
    for srcline in ("    'sub/ass_mp.c',\n",
                    "    'sub/osd_libass.c',\n",
                    "    'sub/sd_ass.c',\n"):
        if srcline in text:
            text = text.replace(srcline, '', 1)

    # (e) Add the replacement stub source. Anchor on a sibling sub/ source
    #     that always remains (sub/dec_sub.c) and is not touched above.
    stub_line = "    'sub/stub_libass.c',\n"
    anchor = "    'sub/dec_sub.c',\n"
    if stub_line not in text:
        if anchor not in text:
            raise RuntimeError(
                f"Anchor `sub/dec_sub.c` not found in {path}; cannot add the "
                f"replacement stub source.")
        text = text.replace(anchor, anchor + stub_line, 1)

    if text == orig:
        print(f'Already patched: {path}')
        return
    with open(path, 'w') as f:
        f.write(text)
    print(f'Patched: {path}')


# ─── player/command.c ───────────────────────────────────────────────────
#
# Staying file: drops the `#include <ass/ass.h>` (gone with libass headers)
# and rewrites the `libass-version` property getter, which called the now
# unresolvable `ass_library_version()`.

CMD_INCLUDE_OLD = "#include <ass/ass.h>\n"

CMD_GETTER_OLD = (
    "    return m_property_int64_ro(action, arg, ass_library_version());"
)
CMD_GETTER_NEW = (
    "    /* " + MARKER + ": libass stripped from the build. */\n"
    "    return m_property_int64_ro(action, arg, 0);"
)


def patch_command_c(path):
    with open(path) as f:
        text = f.read()
    if MARKER in text:
        print(f'Already patched: {path}')
        return

    changed = False

    if CMD_INCLUDE_OLD in text:
        # Replace with a marker so re-runs are detected and idempotent.
        text = text.replace(
            CMD_INCLUDE_OLD,
            "/* " + MARKER + ": #include <ass/ass.h> removed (libass "
            "stripped). */\n", 1)
        changed = True
    else:
        raise RuntimeError(
            f"`#include <ass/ass.h>` not found in {path} — mpv source layout "
            f"changed.")

    if CMD_GETTER_OLD in text:
        text = text.replace(CMD_GETTER_OLD, CMD_GETTER_NEW, 1)
        changed = True
    else:
        raise RuntimeError(
            f"`ass_library_version()` call not found in {path} — mpv source "
            f"layout changed.")

    if changed:
        with open(path, 'w') as f:
            f.write(text)
        print(f'Patched: {path}')


def main():
    if len(sys.argv) < 2:
        print(f'Usage: {sys.argv[0]} <mpv_src_dir>')
        sys.exit(1)
    src = sys.argv[1]
    write_stub(src)
    patch_meson(os.path.join(src, 'meson.build'))
    patch_command_c(os.path.join(src, 'player', 'command.c'))


if __name__ == '__main__':
    main()
